### ISSUE TITLE
Stacking tornado_session.Results.close calls doesn't close any connection

### ISSUE THREAD

**Issue by emehrkay** [gmr/queries#13]
Maybe I am doing something wrong, but if I were to simply wait until later in the execution stack to call close on a tornado result, it never closes.

~~~python
conn = queries.queries.TornadoSession(pool_max_size=3)
....
res1 = yield conn.result('some query')
res2 = yield conn.result('some query')
res3 = yield conn.result('some query')

res1.free()
res2.free()
res3.free()

res4 = yield conn.result('some query')
# PoolFullError: Pool <queries.pool.Pool object at $ID> is at its maximum capacity
res4.free()
~~~

If I were to free a result before using the connection again, things work fine. (I even tested with a counter by inspecting the conn_pool_manager._pools dict)

Am I missing something?

**Comment by djt5019** [comment]
If I recall correctly the `free` method on the `Results` object from a `TornadoSession` is a coroutine.  I think you need to `yield resX.free()`.

**Comment by gmr** [comment]
Yeah weird, I don't see why I made that a coroutine... I should clean that up.
