### ISSUE TITLE
Is there an executemany using the TornadoSession?

### ISSUE THREAD

**Issue by Knights22** [gmr/queries#15]
I have seen the concurrent queries example by wrapping the sql statements in a list but that only works if you know beforehand how many queries you are going to send. Is there a method to executemany such as i would do below?

`cars = (
    (1, 'Audi', 52642),
    (2, 'Mercedes', 57127),
    (3, 'Skoda', 9000),
    (4, 'Volvo', 29000),
    (5, 'Bentley', 350000),
    (6, 'Citroen', 21000),
    (7, 'Hummer', 41400),
    (8, 'Volkswagen', 21600)
)

cur.executemany(query, cars)`

Thanks in advance!

**Comment by gmr** [comment]
Unfortunately not currently. I've ran into circumstance for this myself, but haven't had time to implement.

**Comment by gmr** [comment]
I'll track the feature implementation in #17, thanks for inquiring!
