### ISSUE TITLE
Password with %5D login failed

### ISSUE THREAD

**Issue by lycheng** [gmr/queries#22]
Hi, 

I found that my password include `%5D` and it failed to login. And the same password I use `psycopg2` library is OK.

It's some wrong my code or anything i ignored?

Thanks.

**Comment by lycheng** [comment]
https://github.com/gmr/queries/blob/master/queries/session.py#L283 

I found that here `kwargs` the value of key `password` chanage to `]`, I think that is the bug?

**Comment by gmr** [comment]
Ah yes, because it works off of a URL, your %5D == ]. You should encode that... for example
``foo%5Dbar`` becomes ``foo%255Dbar``.

**Comment by lycheng** [comment]
All right, thanks :)
