### ISSUE TITLE
Requirement psycopg2<2.8 prevents Python 3.8 support

### ISSUE THREAD

**Issue by ParkerD559** [gmr/queries#36]
See https://github.com/psycopg/psycopg2/issues/854, the current requirements of `psycopg2>=2.5.1,<2.8` attempts to install psycopg2-2.7.7, but this version is incompatible with python 3.8 due to the above issue, which was fixed in 2.8

**Comment by gmr** [comment]
This is fixed with 2.1.0 which will be released today.
