### ISSUE TITLE
psycopg2 as a dependency

### ISSUE THREAD

**Issue by louis77** [gmr/queries#37]
Installing queries via pip install psycopg2 as a dependency. However on many platforms now psycopg2-binary package must be used because of lack of PG dev packages available. For instance, AWS Lambda, Azure Functions etc.

Therefore I believe that either psycopg2 should be removed as a direct dependency and let the user manually add the approprate package or offer a queries-binary variant.

**Comment by stephane-klein** [comment]
Same issue for me @gmr

**Comment by stephane-klein** [comment]
@gmr what do you think about this Pull Request https://github.com/gmr/queries/pull/39 ?
