### ISSUE TITLE
python script cannot run by windows task scheduler with a simple "import queries"

### ISSUE THREAD

**Issue by meilao3rd** [gmr/queries#40]
Python script runs fine but not by windows task scheduler. It exits with (0x1) in task scheduler. 
try the following script:

import logging
import pandas as pd
import sqlalchemy
import pprint
#import queries
from urllib.request import Request, urlopen
import datetime

logging.basicConfig(filename='./logs/mylog.log', filemode='a', format='%(asctime)s.%(msecs)03d %(name)s %(levelname)s %(message)s', datefmt='%Y-%m-%d,%H:%M:%S', level=logging.INFO)

logging.info("===== process started =====")

**Comment by meilao3rd** [comment]
It seems an issue of pgsql https://github.com/psycopg/psycopg2/issues/1138

**Comment by gmr** [comment]
Thanks for rollowing up
